project_name: 'VAE'
train_name: 'base_savemodel'


roots : './data'
weight : 'wb'
yml : 'yml/train.yml'

train : True
downloads : True
shuffle : True

learning_rate : 1e-3
seed : 1234


batch_size : 128 
workers : 0
epochs : 10
image_size : 784 #28*28
h_dim : 32
z_dim : 16